### ISSUE TITLE
Swagger doc generation with composite nested fields

### ISSUE THREAD

**Issue by errietta** [oxan/djangorestframework-dataclasses#14]
If you have something like:
```
@dataclass
class Person():
    name: str


@dataclass
class Company():
    people: List[Person]


class PersonSerializer(DataclassSerializer):
    class Meta:
        dataclass = Person

class CompanySerializer(DataclassSerializer):
    class Meta:
        dataclass = Company
```

If I use `get_schema_view` to generate an openapi schema, the result for a view using `CompanySerializer` is this:

```
              properties:
                people:
                  type: array
                  items:
                    type: object # <---- no typing for the child elements!
                  writeOnly: true
              required:
              - people

```

However, if I use `PeopleSerializer` directly, it generates a schema for all fields as expected.
I'm not sure if this is a problem with DRF dataclass serializer or somewhere else, because `get_fields()` on the serializer is definitely returning all fields as expected, and not sure how to debug this. Any ideas on why this is happening?
