### ISSUE TITLE
For nested dataclass serializers, prefix with the name of dataclass so drf-spectacular doesn't combine components

### ISSUE THREAD

**Issue by ford-carta** [oxan/djangorestframework-dataclasses#55]
## Problem
The generated nested dataclass serializers are called DataclassSerializer, making it hard to differentiate them. When used with drf-spectacular this leads to unfortunate collisions that override the different types.
```py
OrderedDict([('messages',
              MessageSerializer(many=True):
                  contacts = ContactSerializer(many=True):
                      name = CharField()
                  id = CharField()
                  message_timestamp = DateTimeField()
                  attachments = DataclassSerializer(many=True):
                      id = UUIDField()
                      filename = CharField()
                      url = CharField()),
             ('firm',
              DataclassSerializer(dataclass=<class 'fund_admin.comms.domain.FirmDomain'>):
                  id = IntegerField()
                  firm_name = CharField()
             ('entity',
              DataclassSerializer(dataclass=<class 'fund_admin.comms.domain.EntityDomain'>):
                  id = IntegerField()
                  entity_name = CharField()
```
This is what get_fields returns for my serializer. As you can see, the generated DataclassSerializers have the name `DataclassSerializer`. When this is put through drf-spectacular, this causes the Components to all be called "Dataclass" (Serializer postfix is stripped) and the last one to be evaluated (most nested one in this case) overrides the type in the schema.

## Proposal: Prefix serializer class name with dataclass name
On line 512 in `rest_framework_dataclasses/serializers.py`
```py
def build_dataclass_field(self, field_name: str, type_info: TypeInfo) -> SerializerFieldDefinition:
...
    # add this line at 512
    class NewClass(field_class):
        pass
    NewClass.__name__ = type_info.base_type.__name__ +  "Serializer"
    return NewClass, field_kwargs

```

## Generated schema showing that attachments override FirmDomain and EntityDomain
```yml
    Dataclass:
      type: object
      properties:
        id:
          type: string
          format: uuid
        filename:
          type: string
        url:
          type: string
      required:
      - filename
      - id
      - url
```
cc: @tfranzel
@oxan
